### PR TITLE
Update syntax

### PR DESCRIPTION
**Pull request by cpariwat**
### Note
Returns within inline callbacks are no longer allowed in Rails 4.1
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#usage-of-return-within-inline-callback-blocks

### CODE REVIEW

**Comment by dg-rr** [comment]
@cpariwat @jhdavids8 Any reason why this PR was never merged?

**Comment by cpariwat** [comment]
@pg-randy I opened this pr as a part of rails version upgrade ticket but it was deprioritized at the time. please feel free to close this if it becomes irrelevant.

**Comment by dg-rr** [comment]
@cpariwat Actually, we're back working on the Rails upgrade now and would like to merge this in to help resolve some test failures. Can I go ahead and merge it?

**Comment by cpariwat** [comment]
@pg-randy I'll leave it up to you guys at Pathgather to decide. please check if it's compatible with the current configuration.

**Review by dg-rr — APPROVED** [review]

**Pull request merged**
